# Generated by Django 3.2.7 on 2021-09-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('description', models.TextField(max_length=300, verbose_name='description')),
                ('url', models.TextField(max_length=600, verbose_name='url')),
                ('price', models.FloatField(verbose_name='price')),
                ('popular', models.BooleanField(verbose_name='popular')),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email_address')),
                ('phonenumber', models.PositiveIntegerField(max_length=10, unique=True, verbose_name='phone_number')),
                ('member_since', models.DurationField()),
                ('online', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('order_delivered', models.PositiveIntegerField(default=1379)),
                ('average_rating', models.PositiveSmallIntegerField(choices=[(1, 'One Star'), (2, 'Two Star'), (3, 'Three Star'), (4, 'Four Star'), (5, 'Five Star')], default=(1, 'One Star'), verbose_name='rating')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('store_category', models.CharField(choices=[('K', 'Kirana Store'), ('S', 'SuperMarket')], default=('K', 'Kirana Store'), max_length=10, verbose_name='category')),
                ('street_address', models.TextField(max_length=300, verbose_name='address')),
                ('pincode', models.PositiveIntegerField(max_length=6, verbose_name='pincode')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('average_rating', models.PositiveSmallIntegerField(choices=[(1, 'One Star'), (2, 'Two Star'), (3, 'Three Star'), (4, 'Four Star'), (5, 'Five Star')], default=(1, 'One Star'), verbose_name='rating')),
                ('average_packaging_time', models.PositiveIntegerField(default=30, verbose_name='packaging_time')),
                ('products', models.ManyToManyField(to='stores.Product')),
            ],
        ),
    ]
