# Generated by Django 3.2.7 on 2021-09-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('rider_name', models.CharField(max_length=100)),
                ('store_delivery', models.IntegerField()),
                ('rider_store', models.IntegerField()),
                ('packaging_time', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
